# https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "18:22"
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - dependencies/dependabot
      - dependencies/npm
